(println "---defroutes")
(defvar myname "m0cchi")
(defun greeting (name)
  (str "hello, " name))
(defroutes context
  ("/" (read (file "file/index.html")))
  ("/name" (template (read (file "file/template.list.html"))))
  ("/code-runner" (template (read (file "file/code-runner.html"))))
  ("/img/preview.png" (read (file "file/img/preview.png")))
  ("/byte" (new java.lang.String (read (file "bootstrap.lisp"))))
  ("/greeting" "hello"))
(println "---start http service")
(http-service 18080 context)
